import { getBlogPostBySlug, getRelatedPosts } from "@/lib/blog"
import { RelatedPosts } from "@/components/related-posts"
import { notFound } from "next/navigation"
import Image from "next/image"
import { CalendarIcon, ClockIcon, TagIcon } from "lucide-react"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import Link from "next/link"

interface BlogPostPageProps {
  params: {
      slug: string
        }
        }

        export default function BlogPostPage({ params }: BlogPostPageProps) {
          const post = getBlogPostBySlug(params.slug)

            if (!post) {
                notFound()
                  }

                    const relatedPosts = getRelatedPosts(params.slug)

                      return (
                          <>
                                <div className="container mx-auto px-4 py-8 max-w-4xl">
                                        <article className="space-y-8">
                                                  {/* Header */}
                                                            <header className="space-y-4">
                                                                        <div className="flex flex-wrap gap-2">
                                                                                      {post.categories.map((category) => (
                                                                                                      <Badge key={category} variant="secondary">
                                                                                                                        {category}
                                                                                                                                        </Badge>
                                                                                                                                                      ))}
                                                                                                                                                                  </div>

                                                                                                                                                                              <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight">{post.title}</h1>

                                                                                                                                                                                          <div className="flex items-center gap-4 text-muted-foreground flex-wrap">
                                                                                                                                                                                                        <div className="flex items-center gap-2">
                                                                                                                                                                                                                        <CalendarIcon className="h-4 w-4" />
                                                                                                                                                                                                                                        <time dateTime={post.date}>
                                                                                                                                                                                                                                                          {new Date(post.date).toLocaleDateString("en-US", {
                                                                                                                                                                                                                                                                              month: "long",
                                                                                                                                                                                                                                                                                                  day: "numeric",
                                                                                                                                                                                                                                                                                                                      year: "numeric",
                                                                                                                                                                                                                                                                                                                                        })}
                                                                                                                                                                                                                                                                                                                                                        </time>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                    <ClockIcon className="h-4 w-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                    <span>{post.readingTime}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Avatar>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <AvatarImage src={post.author.avatar} alt={post.author.name} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <AvatarFallback>{post.author.name.charAt(0)}</AvatarFallback>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Avatar>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="font-medium">{post.author.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-muted-foreground">{post.author.role}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Featured Image */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="relative aspect-video overflow-hidden rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      src={post.coverImage || "/placeholder.svg"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alt={`Featured image for ${post.title}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fill
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              priority
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="prose prose-lg dark:prose-invert max-w-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dangerouslySetInnerHTML={{ __html: post.content }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <footer className="border-t pt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-wrap gap-2 items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <TagIcon className="h-4 w-4 text-muted-foreground" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {post.tags.map((tag) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Badge key={tag} variant="outline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {tag}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Badge>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-6 flex justify-between items-center flex-wrap gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button variant="outline" asChild>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/">← Back to Blog</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Related Posts Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <RelatedPosts posts={relatedPosts} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                